package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.JTextArea;

import database.DatabaseGetSelect;
import database.DatabaseInsert;

/**
 * 
 * @author
 */
public class ReservationWindow extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private JTextArea textArea;

	/**
	 * Creates new form ReservationWindow
	 */
	public ReservationWindow(JTextArea textArea) {
		this.textArea = textArea;
		initComponents();	
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "rawtypes" })
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		fNTF = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		lNTF = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		idTF = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		cityTF = new javax.swing.JTextField();
		countryTF = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		emailTF = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		roomTF = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		aDTF = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		dDTF = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		priceTF = new javax.swing.JTextField();
		bookButton = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		offerList = new javax.swing.JList();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Reservation");
		setResizable(false);

		jLabel1.setText("First Name*");
		jLabel1.setToolTipText("");

		fNTF.setColumns(10);

		jLabel2.setText("Last Name*");

		lNTF.setColumns(10);

		jLabel3.setText("ID*");

		idTF.setColumns(10);
		idTF.setToolTipText("First Name");

		jLabel4.setText("City");

		cityTF.setColumns(10);

		countryTF.setColumns(10);

		jLabel5.setText("Country");

		emailTF.setColumns(10);

		jLabel6.setText("Email");

		jLabel7.setText("Room*");

		roomTF.setColumns(10);

		jLabel8.setText("Arrival Date*");

		aDTF.setColumns(10);

		jLabel9.setText("Departure Date*");

		dDTF.setColumns(10);

		jLabel10.setText("Price*");

		priceTF.setColumns(10);

		bookButton.setText("Book");
		bookButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent arg0) {
				book();
			}
		});
		
		offerList.setModel(new javax.swing.AbstractListModel() {
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			
			//get discount names
			String[] strings = getDiscounts();

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});

		
		jScrollPane2.setViewportView(offerList);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1)
												.addComponent(jLabel2)
												.addComponent(jLabel3)
												.addComponent(jLabel4)
												.addComponent(jLabel5)
												.addComponent(jLabel6))
								.addGap(30, 30, 30)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														idTF,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														fNTF,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														lNTF,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														cityTF,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														emailTF,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														countryTF,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(64, 64, 64)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(
																		bookButton)
																.addGroup(
																		layout.createSequentialGroup()
																				.addComponent(
																						jLabel10)
																				.addGap(114,
																						114,
																						114)
																				.addComponent(
																						priceTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel8)
																				.addComponent(
																						jLabel9)
																				.addComponent(
																						jLabel7))
																.addGap(39, 39,
																		39)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						roomTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						dDTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						aDTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGap(18, 18, 18)
								.addComponent(jScrollPane2,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										120, Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(5, 5, 5)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														192,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						idTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel7)
																				.addComponent(
																						roomTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						fNTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel8)
																				.addComponent(
																						aDTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						lNTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel9)
																				.addComponent(
																						dDTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						cityTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel10)
																				.addComponent(
																						priceTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						countryTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel5))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						emailTF,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel6)
																				.addComponent(
																						bookButton))))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		idTF.getAccessibleContext().setAccessibleName("idTF");

		pack();
	}// </editor-fold>

	private void book() {
		makeOffer();
		// check field
		if (idTF.getText().length() == 0 || fNTF.getText().length() == 0
				|| lNTF.getText().length() == 0
				|| roomTF.getText().length() == 0
				|| aDTF.getText().length() == 0 || dDTF.getText().length() == 0
				|| priceTF.getText().length() == 0) {
			JOptionPane.showMessageDialog(null, "Fill text field",
					"Empty text field", JOptionPane.INFORMATION_MESSAGE);
			return;
		}

		if (!checkDate()) {
			JOptionPane.showMessageDialog(null, "Invalid date", "Date",
					JOptionPane.INFORMATION_MESSAGE);
			return;
		}

		if (customerExist()) {// if customer exist
			if (emptyRoom()) {// if room free
				if (makeRental()) {// make rental
					if(!makeOffer()){// offer error
						JOptionPane.showMessageDialog(null, "Can't make offer",
								"Offer error", JOptionPane.ERROR_MESSAGE);
					}
					
				} else {// rental error
					JOptionPane.showMessageDialog(null, "Can't make rental",
							"Rental error", JOptionPane.ERROR_MESSAGE);
				}
			} else {// room not empty
				JOptionPane.showMessageDialog(null, "Room not empty", "Room",
						JOptionPane.INFORMATION_MESSAGE);
			}
		} else {
			if (insertCustomer()) {// create customer
				if (emptyRoom()) {// if room free
					if (makeRental()) {// make rental
						if(!makeOffer()){// offer error
							JOptionPane.showMessageDialog(null, "Can't make offer",
									"Offer error", JOptionPane.ERROR_MESSAGE);
						}
					} else {// rental error
						JOptionPane.showMessageDialog(null,
								"Can't make rental", "Rental error",
								JOptionPane.ERROR_MESSAGE);
					}

				} else {// room not empty
					JOptionPane.showMessageDialog(null, "Room not empty",
							"Room", JOptionPane.INFORMATION_MESSAGE);
				}
			} else {// customer error
				JOptionPane.showMessageDialog(null, "Can't create customer",
						"Customer error", JOptionPane.ERROR_MESSAGE);
			}
		}

	}

	private boolean customerExist() {
		String CUSTOMEREXISTQUERY = "SELECT idCustomer " + "FROM Customer "
				+ "WHERE idCustomer='" + idTF.getText() + "'";

		DatabaseGetSelect customerExist = new DatabaseGetSelect(textArea,
				CUSTOMEREXISTQUERY);

		ResultSet rs = customerExist.getResult();
		if (rs != null) {
			try {
				if (!rs.next()) {
					return false;
				} else {
					return true;
				}
			} catch (SQLException e) {
				return false;
			} finally {
				customerExist.closeAll();
			}
		} else {
			return false;
		}

	}

	private boolean emptyRoom() {
		String EMPTYROOMQUERY = "SELECT idRoom " + "FROM Room "
				+ "WHERE idRoom='" + roomTF.getText() + "' AND "
				+ "idRoom not in " + "(SELECT idRoom " + "FROM Rental "
				+ "WHERE (date(arrivalDate)>='" + aDTF.getText()
				+ "' AND date(arrivalDate)<'" + dDTF.getText() + "') OR "
				+ "(date(arrivalDate)<='" + aDTF.getText()
				+ "' AND date(departureDate)>'" + aDTF.getText() + "'))";

		DatabaseGetSelect emptyRoom = new DatabaseGetSelect(textArea,
				EMPTYROOMQUERY);

		ResultSet rs = emptyRoom.getResult();
		if (rs != null) {
			try {
				if (!rs.next()) {
					return false;
				} else {
					return true;
				}
			} catch (SQLException e) {
				return false;
			} finally {
				emptyRoom.closeAll();
			}
		} else {
			return false;
		}

	}

	private boolean insertCustomer() {
		String INSERTCUSTOMER = "INSERT INTO Customer(`idCustomer`, `lastName`," +
				" `firstName`, `city`, `country`, `email`)"
				+ "VALUES ('"
				+ idTF.getText()
				+ "', '"
				+ lNTF.getText()
				+ "', '"
				+ fNTF.getText()
				+ "', '"
				+ cityTF.getText()
				+ "', '"
				+ countryTF.getText() + "', '" + emailTF.getText() + "')";

		DatabaseInsert customerInsert = new DatabaseInsert(textArea,
				INSERTCUSTOMER);

		
		if (customerInsert.getConnectionState() && customerInsert.execute()) {
			customerInsert.closeConnection();
			return true;
		} else {
			return false;
		}

	}

	private boolean makeRental() {

		String MAKERENTAL = "INSERT INTO Rental(idRental, `idRoom`, " +
				"`idCustomer`, `arrivalDate`, `departureDate`, " +
				"`dayPrice`, `checkIn`, `checkOut`, `payed`) "
				+ "VALUES (default, '"
				+ roomTF.getText()
				+ "', '"
				+ idTF.getText()
				+ "', '"
				+ aDTF.getText()
				+ " 12:00:00', '"
				+ dDTF.getText()
				+ " 12:00:00', "
				+ priceTF.getText()
				+ ", "
				+ isCurrentDate()
				+ ", 0, 0)";

		DatabaseInsert makeRental = new DatabaseInsert(textArea, MAKERENTAL);
		
		if (makeRental.getConnectionState() == true && makeRental.execute()) {
			makeRental.closeConnection();
			return true;
		} else {
			return false;
		}
	}

	private String isCurrentDate() {
		SimpleDateFormat formatter = new SimpleDateFormat("YYYY-MM-dd");
		Date now = new Date();

		if (formatter.format(now).equalsIgnoreCase(aDTF.getText())) {
			return "1";
		} else {
			return "0";
		}

	}

	private boolean checkDate() {
		SimpleDateFormat formatter = new SimpleDateFormat("YYYY-MM-dd");
		Date now = new Date();

		if (formatter.format(now).compareTo(aDTF.getText()) > 0
				|| formatter.format(now).compareTo(dDTF.getText()) > 0
				|| aDTF.getText().compareTo(dDTF.getText()) >= 0) {
			return false;
		} else {
			return true;
		}
	}

	private boolean makeOffer() {

		int[] indices = offerList.getSelectedIndices();
		if (indices.length == 0) {
			return true;
		} else {
			for (int i : indices) {
				addOffer(i+1);
			}
			return true;
		}
	}
	
	private boolean addOffer(int discountID){
		System.out.println("Discount: "+discountID);
		String GETRENTALID = "SELECT idRental " +
				"FROM Rental " +
				"WHERE arrivalDate = '"+aDTF.getText()+ " 12:00:00' AND " +
						"idRoom = '"+roomTF.getText()+"' AND "+
						"idCustomer = '"+idTF.getText()+"'";
		
		DatabaseGetSelect getRentalID = new DatabaseGetSelect(textArea,
				GETRENTALID);
		
		ResultSet rs = getRentalID.getResult();
		
		if(rs != null){
			try {
				rs.next();
				int idRental = rs.getInt("idRental");
				getRentalID.closeAll();

				String  INSERTOFFER = 
						"INSERT INTO Offer " +
						"VALUES(default, "+idRental+", "+discountID+")";
				DatabaseInsert insertOffer = new DatabaseInsert(textArea, 
						INSERTOFFER);
				if (insertOffer.getConnectionState() == true && 
						insertOffer.execute()) {
					insertOffer.closeConnection();
					return true;
				} else {
					return false;
				}
				
						
			} catch (SQLException e) {
				System.out.println("Error");
				return false;

			}
		}else{
			System.out.println("exit");
			return false;
		}
		
	}
	private String[] getDiscounts(){
		ArrayList<String> temp = new ArrayList<String>();
		String GETDISCOUNTS = "SELECT name " +
							"FROM Discount";
		
		DatabaseGetSelect getDiscounts = new DatabaseGetSelect(textArea,
				GETDISCOUNTS);
		
		ResultSet rs = getDiscounts.getResult();
		
		if (rs != null) {
			try {
				while(rs.next()){
					temp.add(rs.getString("name"));
				}
			} catch (SQLException e) {
				return null;
			}finally{
				getDiscounts.closeAll();
			}
		}
		String[] type = new String[temp.size()];
		for(int i = 0;i<temp.size();i++){
			type[i] = temp.get(i);
		}
		return type;
	}

	// Variables declaration - do not modify
	private javax.swing.JTextField aDTF;
	private javax.swing.JButton bookButton;
	private javax.swing.JTextField cityTF;
	private javax.swing.JTextField countryTF;
	private javax.swing.JTextField dDTF;
	private javax.swing.JTextField emailTF;
	private javax.swing.JTextField fNTF;
	private javax.swing.JTextField idTF;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextField lNTF;
	@SuppressWarnings("rawtypes")
	private javax.swing.JList offerList;
	private javax.swing.JTextField priceTF;
	private javax.swing.JTextField roomTF;
	// End of variables declaration
}
